openapi: 3.0.0
info:
  title: API Orquestador
  description: API para gestionar la creación de pedidos y actualizar inventarios mediante la coordinación de microservicios de productos y pedidos.
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Servidor local del orquestador

paths:
  /:
    get:
      summary: Verificar el funcionamiento del orquestador
      responses:
        '200':
          description: Orquestador funcionando correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Orquestador funcionando correctamente

  /orquestador/pedido:
    post:
      summary: Crear un nuevo pedido y actualizar el inventario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                cliente:
                  type: string
                  example: Juan Perez
                detalles:
                  type: array
                  items:
                    type: object
                    properties:
                      producto_id:
                        type: integer
                        example: 123
                      cantidad:
                        type: integer
                        example: 2
      responses:
        '201':
          description: Pedido creado y el inventario actualizado con éxito
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Pedido creado y el inventario actualizado con éxito
        '400':
          description: Error en el proceso de creación del pedido o inventario insuficiente
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Inventario insuficiente para el producto ID 123
        '500':
          description: Error interno al crear el pedido o actualizar el inventario
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Error al crear el pedido

components:
  schemas:
    Pedido:
      type: object
      properties:
        cliente:
          type: string
        detalles:
          type: array
          items:
            type: object
            properties:
              producto_id:
                type: integer
              cantidad:
                type: integer
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
